[package]
name = "frida"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ec = "0.4"
ark-ff = "0.4"
ark-bn254 = "0.4"
rand = "0.8.5"
ark-serialize = "0.4"
util = { path = "../util" }